export const PaymentErrors = [
  { error: 'pending_contingency', message: 'Estamos processando o pagamento. Não se preocupe, em menos de 2 dias úteis informaremos por e-mail se foi creditado' },
  { error: 'pending_review_manual', message: 'Estamos processando seu pagamento. Não se preocupe, em menos de 2 dias úteis informaremos por e-mail se foi creditado ou se necessitamos de mais informação' },
  { error: 'cc_rejected_bad_filled_card_number', message: 'Revise o número do cartão' },
  { error: 'cc_rejected_bad_filled_date', message: 'Revise a data de vencimento.' },
  { error: 'cc_rejected_bad_filled_other', message: 'Revise os dados.' },
  { error: 'cc_rejected_bad_filled_security_code', message: 'Revise o código de segurança do cartão.' },
  { error: 'cc_rejected_blacklist ', message: 'Não pudemos processar seu pagamento' },
  { error: 'cc_rejected_call_for_authorize', message: 'Você deve autorizar ao payment_method_id o pagamento do valor ao Mercado Pago' },
  { error: 'cc_rejected_card_disabled', message: 'Ligue para o payment_method_id para ativar seu cartão. O telefone está no verso do seu cartão' },
  { error: 'cc_rejected_card_error', message: 'Não conseguimos processar seu pagamento' },
  { error: 'cc_rejected_duplicated_payment', message: 'Você já efetuou um pagamento com esse valor. Caso precise pagar novamente, utilize outro cartão ou outra forma de pagamento.' },
  { error: 'cc_rejected_high_risk', message: 'Seu pagamento foi recusado. Escolha outra forma de pagamento. Recomendamos meios de pagamento em dinheiro' },
  { error: 'cc_rejected_insufficient_amount', message: 'O payment_method_id possui saldo insuficiente' },
  { error: 'cc_rejected_invalid_installments', message: 'O payment_method_id não processa pagamentos em installments parcelas' },
  { error: 'cc_rejected_max_attempts', message: 'Você atingiu o limite de tentativas permitido. Escolha outro cartão ou outra forma de pagamento' },
  { error: 'cc_rejected_other_reason', message: 'payment_method_id não processa o pagamento' },
  { error: 'cc_rejected_card_type_not_allowed', message: 'O pagamento foi rejeitado porque o usuário não tem a função crédito habilitada em seu cartão multiplo (débito e crédito)' },
];
